// Create web server
// Start web server
// Create an endpoint
// Create a comment
// Read all comments
// Read a comment
// Update a comment
// Delete a comment
// Stop web server
// Test the endpoint